#include "shader_defs.h"

#define DEFINE_INPUT_CONSTANTS DEFINE_BUFFER_0;
#define GET_ITEM_INPUT_CONSTANTS(element_index) GET_ITEM_BUFFER_0(element_index)

#define DEFINE_INPUT_POTENTIAL DEFINE_BUFFER_1;
#define GET_ITEM_INPUT_POTENTIAL(element_index) GET_ITEM_BUFFER_1(element_index)

#define DEFINE_INPUT_X DEFINE_BUFFER_2;
#define DEFINE_DEVICE_LOCAL_FXG DEFINE_BUFFER_3;
#define DEFINE_DEVICE_LOCAL_YG DEFINE_BUFFER_4;
#define DEFINE_OUTPUT_ENERGY DEFINE_BUFFER_5;

PROGRAM_HEADER

DEFINE_INPUT_CONSTANTS

DEFINE_INPUT_POTENTIAL
DEFINE_INPUT_X
DEFINE_DEVICE_LOCAL_FXG
DEFINE_DEVICE_LOCAL_YG
DEFINE_OUTPUT_ENERGY

#define TO_CM 2.194746e5
#define TO_EV 27.211608
#define CM_TO_AU 0.000004556335267302901346306204494
#define EV_TO_AU 3.6740e-2

MAIN_RETURN_TYPE main() {

    FLOAT_TYPE reduced_mass =
        (GET_ITEM_INPUT_CONSTANTS(0).mass_atom_0 * GET_ITEM_INPUT_CONSTANTS(0).mass_atom_1) /
        (GET_ITEM_INPUT_CONSTANTS(0).mass_atom_0 + GET_ITEM_INPUT_CONSTANTS(0).mass_atom_1) *
        1836.12;

    FLOAT_TYPE hh =
        GET_ITEM_INPUT_CONSTANTS(0).integration_step * GET_ITEM_INPUT_CONSTANTS(0).integration_step;

    for (INT_TYPE i = 0; i < 32; i++) {}

    MAIN_RETURN_STMT;
}
